# =============================================================================
# build_defaults_master_doc.R -- render the master CSV as a readable document
# =============================================================================
#
# reference/defaults_master.csv is the authority but is long-format and awkward
# to read. This renders it as reference/DEFAULTS_MASTER.md: wide tables per
# object, plus the table that did not exist anywhere before -- the EFFECTIVE
# value of every parameter for every sub-category, including the overrides and
# biological zeros that resolve_subcat_default() applies at run time.
#
# Generated, never hand-edited. Edit the CSV and re-run.
#
# Usage (from project root):
#   Rscript scripts/build_defaults_master_doc.R
# =============================================================================

if (basename(getwd()) == "scripts") setwd("..")
suppressMessages({
  for (f in list.files("R", pattern = "[.]R$", full.names = TRUE))
    if (!grepl("^_", basename(f))) source(f)
})

fmt <- function(x) {
  if (is.null(x) || length(x) == 0) return("")
  if (is.na(x)) return("")
  if (is.logical(x)) return(if (x) "yes" else "no")
  n <- suppressWarnings(as.numeric(x))
  if (!is.na(n)) format(n, scientific = FALSE, trim = TRUE, drop0trailing = TRUE)
  else gsub("\\|", "\\\\|", as.character(x))
}
tbl <- function(d, cols = names(d)) {
  c(paste0("| ", paste(cols, collapse = " | "), " |"),
    paste0("|", paste(rep("---", length(cols)), collapse = "|"), "|"),
    vapply(seq_len(nrow(d)), function(i)
      paste0("| ", paste(vapply(cols, function(k) fmt(d[[k]][i]),
                                character(1)), collapse = " | "), " |"),
      character(1)))
}

M <- .defaults_master
out <- c(
  "# Defaults master",
  "",
  sprintf("Generated %s from `reference/defaults_master.csv` by `scripts/build_defaults_master_doc.R`. Do not edit this file; edit the CSV.",
          Sys.Date()),
  "",
  "This is the single authority for every IPCC default the app ships. `R/load_defaults.R` builds `PARAM_CATALOGUE`, `MMS_DEFAULTS`, `MMS_FRAC_DEFAULTS_2019` and the per-sub-category lists from the CSV at start-up, and every other surface (the Excel template, the translator prompts, the published guides) derives from those objects. `scripts/verify_defaults.R` checks all 14 surfaces against it and runs in CI.",
  "",
  sprintf("- %d value rows across %d objects", nrow(M), length(unique(M$object))),
  sprintf("- %d rows carry a review provenance reference",
          sum(nzchar(M$review_round), na.rm = TRUE)),
  "")

out <- c(out, "## Parameter catalogue", "",
  "The 25 parameters. `ipcc_default` is the generic value; where a sub-category overrides it, see the effective-values table below.", "",
  tbl(PARAM_CATALOGUE,
      c("parameter", "unit", "ipcc_default", "suggested_uncertainty_pct",
        "suggested_lower_bound", "suggested_upper_bound",
        "suggested_distribution", "param_type", "param_tier",
        "user_reducible", "ipcc_ref")), "")

out <- c(out, "## Manure management systems", "",
  "`ipcc_variant` records which IPCC sub-type each row models. It exists because IPCC splits several systems into variants with different coefficients, and every coefficient on a row must come from the variant named here.", "",
  tbl(MMS_DEFAULTS,
      c("id", "versions", "mcf_tropical", "mcf_tropical_dry", "mcf_temperate",
        "mcf_boreal", "ef3", "ipcc_variant")), "",
  "### Nitrogen loss fractions (2019R Table 10.22, Other Cattle)", "",
  tbl(MMS_FRAC_DEFAULTS_2019), "")

out <- c(out, "## Per-sub-category overrides", "",
  tbl(data.frame(
    sub_category = names(CFI_BY_SUBCAT),
    Cfi = unlist(CFI_BY_SUBCAT),
    C   = unlist(C_GROWTH_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    BW  = unlist(LW_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    MW  = unlist(MW_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    WG  = unlist(WG_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    stringsAsFactors = FALSE)), "")

# --- the table that did not exist before -----------------------------------
out <- c(out, "## Effective value of every parameter, per sub-category", "",
  "What the app actually fills in, from `resolve_subcat_default()`: the generic default, then any per-sub-category override, then the biological zeros (no milk, fat or milk protein for males; no pregnancy for males or calves; no work hours except oxen). `source` distinguishes them.", "",
  "| sub_category | parameter | value | distribution | source |",
  "|---|---|---|---|---|")
for (sc in ANIMAL_SUBCATEGORIES) for (prm in PARAM_CATALOGUE$parameter) {
  r <- tryCatch(resolve_subcat_default(sc, prm), error = function(e) NULL)
  if (is.null(r)) next
  gen <- PARAM_CATALOGUE$ipcc_default[PARAM_CATALOGUE$parameter == prm]
  src <- if (identical(r$data_source, "biological_zero")) "biological zero"
         else if (!is.na(r$value) && !is.na(gen) && !isTRUE(all.equal(r$value, gen)))
           "sub-category override"
         else "catalogue default"
  out <- c(out, sprintf("| %s | %s | %s | %s | %s |", sc, prm,
                        fmt(r$value), r$distribution, src))
}

out <- c(out, "", "## Global warming potentials", "",
  tbl(data.frame(
    set = rep(names(GWP_VALUES), each = 2),
    gas = unlist(lapply(GWP_VALUES, names)),
    value = unlist(GWP_VALUES), stringsAsFactors = FALSE)), "",
  "## Regional body-weight benchmark", "",
  "The only parameter with a defensible continental IPCC lookup; the other benchmarks were withdrawn after review because their sources could not be found in the guidelines.", "",
  tbl(IPCC_DEFAULTS_BY_REGION), "")

writeLines(out, "reference/DEFAULTS_MASTER.md", useBytes = TRUE)
cat("wrote reference/DEFAULTS_MASTER.md (", length(out), " lines)\n", sep = "")
