# =============================================================================
# build_defaults_master_doc.R -- render the master CSV as a readable document
# =============================================================================
#
# reference/defaults_master.csv is the authority but is long-format and awkward
# to read. This renders it as reference/DEFAULTS_MASTER.md: wide tables per
# object, plus the table that did not exist anywhere before -- the EFFECTIVE
# value of every parameter for every sub-category, including the overrides and
# biological zeros that resolve_subcat_default() applies at run time.
#
# Generated, never hand-edited. Edit the CSV and re-run.
#
# Usage (from project root):
#   Rscript scripts/build_defaults_master_doc.R
# =============================================================================

if (basename(getwd()) == "scripts") setwd("..")
suppressMessages({
  for (f in list.files("R", pattern = "[.]R$", full.names = TRUE))
    if (!grepl("^_", basename(f))) source(f)
})

fmt <- function(x) {
  if (is.null(x) || length(x) == 0) return("")
  if (is.na(x)) return("")
  if (is.logical(x)) return(if (x) "yes" else "no")
  n <- suppressWarnings(as.numeric(x))
  if (!is.na(n)) format(n, scientific = FALSE, trim = TRUE, drop0trailing = TRUE)
  else gsub("\\|", "\\\\|", as.character(x))
}
tbl <- function(d, cols = names(d)) {
  c(paste0("| ", paste(cols, collapse = " | "), " |"),
    paste0("|", paste(rep("---", length(cols)), collapse = "|"), "|"),
    vapply(seq_len(nrow(d)), function(i)
      paste0("| ", paste(vapply(cols, function(k) fmt(d[[k]][i]),
                                character(1)), collapse = " | "), " |"),
      character(1)))
}

M <- .defaults_master
out <- c(
  "# Defaults master",
  "",
  sprintf("Generated %s from `reference/defaults_master.csv` by `scripts/build_defaults_master_doc.R`. Do not edit this file; edit the CSV.",
          Sys.Date()),
  "",
  "This is the single authority for every IPCC default the app ships. `R/load_defaults.R` builds `PARAM_CATALOGUE`, `MMS_DEFAULTS`, `MMS_FRAC_DEFAULTS_2019` and the per-sub-category lists from the CSV at start-up, and every other surface (the Excel template, the translator prompts, the published guides) derives from those objects. `scripts/verify_defaults.R` checks all 14 surfaces against it and runs in CI.",
  "",
  sprintf("- %d value rows across %d objects", nrow(M), length(unique(M$object))),
  sprintf("- %d rows carry a review provenance reference",
          sum(nzchar(M$review_round), na.rm = TRUE)),
  "")

# --- verification summary --------------------------------------------------
# Every numeric default was read back against the IPCC source text value by
# value. The verdicts live on the master itself; this renders them so the
# document a reader opens shows which values are quoted from IPCC and which
# are not, rather than implying that all of them are.
.numeric_row <- !is.na(suppressWarnings(as.numeric(M$value)))
.vt <- table(M$ipcc_verdict[.numeric_row])
.gloss <- c(
  CONFIRMED = "read at the cited IPCC table or equation",
  INTERPRETED = "a defensible reading of an IPCC category label, not a quotation",
  DEVIATION_DOCUMENTED = "differs from IPCC deliberately, reason on record",
  DEVIATION_OPEN = "differs from IPCC with no recorded reason; needs a decision",
  NOT_IPCC = "a non-IPCC source or a project assumption",
  NO_IPCC_DEFAULT = "IPCC publishes no default for this quantity",
  META = "not a shipped value")
out <- c(out, "## IPCC verification status", "",
  sprintf("All %d numeric values below were checked one at a time against the IPCC source text on 2026-09-11. Each carries its verdict and the exact table it was read from, in the `ipcc_verdict` and `ipcc_source` columns of the CSV. Audit check F33 fails the build if a value is ever added without one.",
          sum(.numeric_row)),
  "",
  "| verdict | meaning | values |", "|---|---|---|")
for (v in names(sort(.vt, decreasing = TRUE)))
  out <- c(out, sprintf("| `%s` | %s | %d |", v, .gloss[[v]], .vt[[v]]))
out <- c(out, "",
  "The `DEVIATION_OPEN` rows are the ones that would move a reported number if resolved. They are listed in full at the end of this document and discussed in `reference/provenance_register.md`.",
  "")

# This document is the INTERNAL reference, so it shows both scopes. The
# user-facing surfaces show tool-wide rows only, because a fallback the
# resolver already varies is not an assumption and saying otherwise
# understates the tool.
.basis_rows <- function(d) {
  vapply(seq_len(nrow(d)), function(i)
    sprintf("| **%s** | %s | %s | `%s` | %s | %s |",
      basis_dimension_label(d$dimension[i]),
      fmt(d$chosen[i]), fmt(d$alternatives[i]),
      gsub(" ", "`, `", d$governs[i], fixed = TRUE),
      fmt(d$ipcc_source[i]), fmt(d$why[i])), character(1))
}
.hdr <- c("| choice | this tool uses | IPCC also publishes | affects | IPCC source | why |",
          "|---|---|---|---|---|---|")
.tw <- basis_tool_wide()
.rs <- DEFAULT_BASIS[DEFAULT_BASIS$scope != "tool_wide", , drop = FALSE]

out <- c(out, "## What the defaults assume", "",
  "Every value in this document is one cell of a much larger IPCC table. Reaching it means choosing a region, a productivity class, a climate and, for manure, a specific system variant. Those choices are the declared basis, held in the master as `DEFAULT_BASIS` and rendered from this one place into the app's Definitions tab, both published guides, the Excel template and the translator prompt.", "",
  sprintf("### Tool-wide assumptions (%d)", nrow(.tw)), "",
  "A compiler cannot vary these from their data, so these are the only ones shown on user-facing surfaces.", "",
  .hdr, .basis_rows(.tw), "",
  sprintf("### Resolved, not assumed (%d) -- internal record only", nrow(.rs)), "",
  "**These are deliberately NOT shown to users as assumptions.** The tool works them out rather than assuming them, so presenting them alongside the rows above would misdescribe it. Kept here so the distinction itself is on the record.", "",
  .hdr, .basis_rows(.rs), "",
  "`MCF`, `EF3` and `FRAC` in the affects column are the per-manure-system coefficient families rather than catalogue parameters.", "")

out <- c(out, "## Parameter catalogue", "",
  "The 25 parameters. `ipcc_default` is the generic value; where a sub-category overrides it, see the effective-values table below.", "",
  tbl(cbind(PARAM_CATALOGUE,
            basis = vapply(PARAM_CATALOGUE$parameter, basis_label, character(1))),
      c("parameter", "unit", "ipcc_default", "basis", "suggested_uncertainty_pct",
        "suggested_lower_bound", "suggested_upper_bound",
        "suggested_distribution", "param_type", "param_tier",
        "user_reducible", "ipcc_ref")), "")

out <- c(out, "## Manure management systems", "",
  "`ipcc_variant` records which IPCC sub-type each row models. It exists because IPCC splits several systems into variants with different coefficients, and every coefficient on a row must come from the variant named here.", "",
  tbl(MMS_DEFAULTS,
      c("id", "versions", "mcf_tropical", "mcf_tropical_dry", "mcf_temperate",
        "mcf_boreal", "ef3", "ipcc_variant")), "",
  "### Nitrogen loss fractions (2019R Table 10.22, Other Cattle)", "",
  tbl(MMS_FRAC_DEFAULTS_2019), "")

out <- c(out, "## Per-sub-category overrides", "",
  "`Ym` is the only default that depends on the guideline edition, so it has a column for each. The 2019 Refinement splits Table 10.12 by livestock category; the 2006 table does not, below feedlot.", "",
  tbl(data.frame(
    sub_category = names(CFI_BY_SUBCAT),
    Cfi = unlist(CFI_BY_SUBCAT),
    C   = unlist(C_GROWTH_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    BW  = unlist(LW_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    MW  = unlist(MW_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    WG  = unlist(WG_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    DE  = unlist(DE_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    CP  = unlist(CP_BY_SUBCAT)[names(CFI_BY_SUBCAT)],
    Ym_2019R = YM_BY_SUBCAT$ym_2019_refinement[
      match(names(CFI_BY_SUBCAT), YM_BY_SUBCAT$sub_category)],
    Ym_2006  = YM_BY_SUBCAT$ym_2006[
      match(names(CFI_BY_SUBCAT), YM_BY_SUBCAT$sub_category)],
    stringsAsFactors = FALSE)), "")

# --- the table that did not exist before -----------------------------------
out <- c(out, "## Effective value of every parameter, per sub-category", "",
  "What the app actually fills in, from `resolve_subcat_default()`: the generic default, then any per-sub-category override, then the biological zeros (no milk, fat or milk protein for males; no pregnancy for males or calves; no work hours except oxen). `source` distinguishes them.", "",
  "| sub_category | parameter | value | distribution | source |",
  "|---|---|---|---|---|")
for (sc in ANIMAL_SUBCATEGORIES) for (prm in PARAM_CATALOGUE$parameter) {
  r <- tryCatch(resolve_subcat_default(sc, prm), error = function(e) NULL)
  if (is.null(r)) next
  gen <- PARAM_CATALOGUE$ipcc_default[PARAM_CATALOGUE$parameter == prm]
  src <- if (identical(r$data_source, "biological_zero")) "biological zero"
         else if (!is.na(r$value) && !is.na(gen) && !isTRUE(all.equal(r$value, gen)))
           "sub-category override"
         else "catalogue default"
  out <- c(out, sprintf("| %s | %s | %s | %s | %s |", sc, prm,
                        fmt(r$value), r$distribution, src))
}

out <- c(out, "", "## Global warming potentials", "",
  tbl(data.frame(
    set = rep(names(GWP_VALUES), each = 2),
    gas = unlist(lapply(GWP_VALUES, names)),
    value = unlist(GWP_VALUES), stringsAsFactors = FALSE)), "",
  "## Regional body-weight benchmark", "",
  "The only parameter with a defensible continental IPCC lookup; the other benchmarks were withdrawn after review because their sources could not be found in the guidelines.", "",
  tbl(IPCC_DEFAULTS_BY_REGION), "")

# --- the open deviations, in full ------------------------------------------
.open <- M[.numeric_row & M$ipcc_verdict == "DEVIATION_OPEN", ]
out <- c(out, "", "## Values that differ from IPCC with no recorded reason", "",
  sprintf("%d of the %d numeric values. Each is a live question, not a known-wrong number: some are roundings of an IPCC cell, some sit between two IPCC tables, and some have no IPCC basis at all. None has been changed on the strength of this pass alone, because several carry review provenance.",
          nrow(.open), sum(.numeric_row)),
  "",
  "| object | key | field | value | what IPCC says |", "|---|---|---|---|---|")
for (i in seq_len(nrow(.open)))
  out <- c(out, sprintf("| %s | %s | %s | %s | %s |",
                        .open$object[i], .open$key[i], .open$field[i],
                        fmt(.open$value[i]), fmt(.open$ipcc_source[i])))
out <- c(out, "",
  "## Full verification record", "",
  "Every numeric value with its verdict and source, in master order.", "",
  "| object | key | field | value | verdict | source |", "|---|---|---|---|---|---|")
.allv <- M[.numeric_row, ]
for (i in seq_len(nrow(.allv)))
  out <- c(out, sprintf("| %s | %s | %s | %s | `%s` | %s |",
                        .allv$object[i], .allv$key[i], .allv$field[i],
                        fmt(.allv$value[i]), .allv$ipcc_verdict[i],
                        fmt(.allv$ipcc_source[i])))

writeLines(out, "reference/DEFAULTS_MASTER.md", useBytes = TRUE)
cat("wrote reference/DEFAULTS_MASTER.md (", length(out), " lines)\n", sep = "")
